files:
  data_directory: "../../room_explorer/.data/FixedOrientationAndAperture.hdf5"
  save_directory: ".model/temp"

network:
  dim_h: 3
  activation: selu

data_loader:
  noise_motor: 0
  noise_sensor: 0
  batch_size: 128
  num_workers: 0
  drop_last: True
  shuffle: True

optimizer:
  lr: 0.003
  weight_decay: 0.0

training:
  n_trials: 10
  n_env_per_training: 10
  n_epochs: 3  #60
  display: True
  gpu: True
