data_directory: "..\\room-explorer\\.datasets\\FixedOrientation_NoAperture-2020-10-06--18-23-37"
save_directory: ".model/experiment_FixedOrientation_NoAperture"

network:
  dim_h: 3

data_loader:
  batch_size: 128
  num_workers: 0
  drop_last: True
  shuffle: True

optimizer:
  lr: 0.003
  weight_decay: 0.0

training:
  n_epochs: 60
  repeat_training: 1
  noise_motor: 0
  sensor_noise: 0
  display: True
  gpu: True
