data_directory: "..\\room-explorer\\.datasets\\30_FixedOrientation_NoAperture-2020-10-06--19-49-24"
save_directory: ".model/test"

network:
  dim_h: 3
  activation: selu

data_loader:
  batch_size: 128
  num_workers: 0
  drop_last: True
  shuffle: True

optimizer:
  lr: 0.003
  weight_decay: 0.0

training:
  n_epochs: 50  #60
  repeat_training: 1
  noise_motor: 0
  sensor_noise: 0
  display: False
  gpu: True
